export const automatizaciones = {
  page: {
    eyebrow: 'Operaciones',
    title: 'Automatizaciones',
    description:
      'Lanza procesos manuales en n8n en puntos clave. Cada tarjeta dispara un flujo configurado por tu asesoría.',
    activityButton: 'Actividad reciente',
    emptyTitle: 'Sin automatizaciones disponibles',
    emptyDescription:
      'No hay procesos activos para tu perfil. Si necesitas alguno, contacta con administración.',
    emptyAdminDescription:
      'Aún no hay automatizaciones en el catálogo. Crea la primera para enlazarla con un workflow de n8n.',
    createButton: 'Nueva automatización',
    notConfiguredTitle: 'n8n no configurado',
    notConfiguredDescription:
      'Falta N8N_WEBHOOK_BASE_URL en el entorno del portal. Las automatizaciones no se pueden lanzar.',
  },
  tabs: {
    run: 'Lanzar',
    access: 'Acceso asesores',
  },
  card: {
    launch: 'Lanzar',
    launching: 'Lanzando…',
    lastRun: 'Última ejecución',
    neverRun: 'Sin ejecuciones',
    adminOnly: 'Solo administración',
    inactive: 'Inactiva',
    launchParamsTitle: 'Parámetros',
    launchParamsSubmit: 'Lanzar',
    launchParamsCancel: 'Cancelar',
    launchParamsRequired: 'Selecciona un valor',
    launchParamsTooLong: 'texto demasiado largo',
    reorderHandle: 'Reordenar',
    edit: 'Editar',
    delete: 'Eliminar',
    confirmDelete:
      'Se eliminará la automatización y su historial de ejecuciones. ¿Continuar?',
    confirmDeleteTitle: 'Eliminar automatización',
    confirmDeleteConfirm: 'Eliminar',
  },
  runStatus: {
    sent: 'Enviado',
    failed: 'Falló',
  },
  lastRunLabel: {
    sent: 'OK',
    failed: 'Error',
  },
  toast: {
    launched: 'Automatización lanzada',
    launchFailed: 'No se pudo lanzar la automatización',
    accessSaved: 'Acceso actualizado',
    accessSaveFailed: 'No se pudo guardar el acceso',
    created: 'Automatización creada',
    createFailed: 'No se pudo crear la automatización',
    orderSaved: 'Orden guardado',
    orderSaveFailed: 'No se pudo guardar el orden',
    invalidInputs: 'Revisa los parámetros de la automatización',
    updated: 'Automatización actualizada',
    updateFailed: 'No se pudo actualizar la automatización',
    deleted: 'Automatización eliminada',
    deleteFailed: 'No se pudo eliminar la automatización',
  },
  runsPanel: {
    title: 'Actividad reciente',
    description: 'Últimas ejecuciones que puedes ver con tu perfil.',
    empty: 'Aún no hay ejecuciones registradas.',
    columns: {
      automation: 'Automatización',
      user: 'Usuario',
      status: 'Estado',
      when: 'Cuándo',
    },
  },
  access: {
    title: 'Acceso asesores',
    description:
      'Activa automatizaciones y define qué asesores pueden lanzarlas.',
    columns: {
      automation: 'Automatización',
      active: 'Activa',
      adminOnly: 'Solo admin',
      visibility: 'Asesores',
      advisors: 'Seleccionados',
      actions: 'Acciones',
    },
    save: 'Guardar',
    saving: 'Guardando…',
    visibility: {
      none: 'Ningún asesor',
      all: 'Todos los asesores',
      selected: 'Asesores seleccionados',
    },
    selectAdvisors: 'Asesores con acceso',
    selectAdvisorsPlaceholder: 'Elige uno o más asesores',
  },
  create: {
    title: 'Nueva automatización',
    titleEdit: 'Editar automatización',
    description:
      'Registra un proceso manual de n8n en el catálogo del portal. La ruta del webhook debe coincidir con el workflow.',
    descriptionEdit:
      'Modifica la definición de la automatización. Los cambios aplican al próximo lanzamiento.',
    fields: {
      slug: 'Identificador',
      title: 'Título',
      description: 'Descripción',
      webhookPath: 'Ruta del webhook',
      icon: 'Icono',
      advisorVisibility: 'Visibilidad para asesores',
      isActive: 'Activa al guardar',
      adminOnly: 'Solo administración',
      inputFields: 'Parámetros de entrada',
    },
    placeholders: {
      title: 'Sincronizar partners Odoo',
      description: 'Relanza la sincronización manual de contactos con Odoo.',
    },
    hints: {
      slug: 'Minúsculas, números y guiones. Se usa en logs y payloads.',
      webhookPath: 'Ruta relativa en n8n, sin dominio (ej. /webhook/sync-odoo-partners).',
      inputFields:
        'Parámetros que se piden al lanzar y viajan al webhook con su clave (select o texto libre).',
      inputKey: 'Clave para el payload: minúsculas, números y _ (ej. mes).',
    },
    inputFieldsEditor: {
      addField: 'Añadir parámetro',
      addSelectField: 'Añadir select',
      addTextField: 'Añadir texto',
      removeField: 'Quitar parámetro',
      type: 'Tipo',
      typeSelect: 'Select',
      typeText: 'Texto',
      key: 'Clave',
      label: 'Etiqueta',
      required: 'Obligatorio',
      defaultValue: 'Opción por defecto',
      defaultTextValue: 'Valor por defecto',
      defaultTextPlaceholder: 'Opcional',
      noDefault: 'Sin valor por defecto',
      options: 'Opciones',
      optionValue: 'Valor',
      optionLabel: 'Etiqueta',
      addOption: 'Añadir opción',
      removeOption: 'Quitar opción',
      empty: 'Sin parámetros: el webhook se lanza directamente.',
    },
    icons: {
      workflow: 'Flujo',
      refresh: 'Actualizar',
      database: 'Base de datos',
      users: 'Usuarios',
    },
    actions: {
      cancel: 'Cancelar',
      submit: 'Crear automatización',
      submitting: 'Creando…',
      submitEdit: 'Guardar cambios',
      submittingEdit: 'Guardando…',
    },
  },
} as const
