export const automatizaciones = {
  page: {
    eyebrow: 'Operaciones',
    title: 'Automatizaciones',
    createButton: 'Nueva automatización',
    configIsLink: 'Configuración Impuesto sobre Sociedades',
    notConfiguredTitle: 'n8n no configurado',
    notConfiguredDescription:
      'Falta N8N_WEBHOOK_BASE_URL en el entorno del portal. Las automatizaciones no se pueden lanzar.',
    activityButton: 'Actividad reciente',
    emptyTitle: 'Sin automatizaciones disponibles',
    emptyDescription:
      'No hay procesos activos para tu perfil. Si necesitas alguno, contacta con administración.',
    emptyAdminDescription:
      'Aún no hay automatizaciones en el catálogo. Crea la primera para enlazarla con un workflow de n8n.',
  },
  tabs: {
    label: 'Vista',
    run: 'Lanzar',
    access: 'Acceso asesores',
  },
  card: {
    launch: 'Lanzar',
    launching: 'Lanzando…',
    lastRun: 'Última ejecución',
    neverRun: 'Sin ejecuciones',
    adminOnly: 'Solo administración',
    inactive: 'Inactiva',
    launchParamsTitle: 'Parámetros',
    launchParamsSubmit: 'Lanzar',
    launchParamsCancel: 'Cancelar',
    launchParamsRequired: 'Selecciona un valor',
    launchParamsTooLong: 'texto demasiado largo',
    reorderHandle: 'Reordenar',
    edit: 'Editar',
    delete: 'Eliminar',
    confirmDelete:
      'Se eliminará la automatización y su historial de ejecuciones. ¿Continuar?',
    confirmDeleteTitle: 'Eliminar automatización',
    confirmDeleteConfirm: 'Eliminar',
  },
  runStatus: {
    sent: 'Enviado',
    failed: 'Falló',
  },
  lastRunLabel: {
    sent: 'OK',
    failed: 'Error',
  },
  toast: {
    launched: 'Automatización lanzada',
    launchFailed: 'No se pudo lanzar la automatización',
    accessSaved: 'Acceso actualizado',
    accessSaveFailed: 'No se pudo guardar el acceso',
    created: 'Automatización creada',
    createFailed: 'No se pudo crear la automatización',
    orderSaved: 'Orden guardado',
    orderSaveFailed: 'No se pudo guardar el orden',
    invalidInputs: 'Revisa los parámetros de la automatización',
    updated: 'Automatización actualizada',
    updateFailed: 'No se pudo actualizar la automatización',
    deleted: 'Automatización eliminada',
    deleteFailed: 'No se pudo eliminar la automatización',
    runsLoadFailed: 'No se pudo cargar la actividad reciente',
  },
  errors: {
    notConfigured:
      'n8n no está configurado. Revisa N8N_WEBHOOK_BASE_URL en el entorno del portal.',
    forbidden: 'No tienes permiso para esta acción.',
    notFound: 'No encontramos la automatización.',
    unknown: 'Algo ha fallado. Inténtalo de nuevo en unos minutos.',
    runsLoadFailed: 'No pudimos cargar la actividad reciente.',
    webhookNotFound:
      'No encontramos ese webhook en n8n. Revisa que la ruta coincida con el workflow.',
    webhookUnauthorized:
      'n8n rechazó la petición. Revisa el secreto compartido con el portal.',
    webhookRateLimited:
      'n8n está recibiendo mucha demanda. Vuelve a intentarlo en unos minutos.',
    webhookServerError:
      'n8n respondió con un error. Inténtalo de nuevo o contacta con administración.',
    webhookTimeout:
      'n8n tardó demasiado en responder. Comprueba el workflow y vuelve a intentarlo.',
    webhookInvalidPath: 'La ruta del webhook no es válida.',
    webhookFailed: 'No se pudo lanzar la automatización.',
  },
  runsPanel: {
    title: 'Actividad reciente',
    description: 'Últimas ejecuciones que puedes ver con tu perfil.',
    empty: 'Aún no hay ejecuciones registradas.',
    loading: 'Cargando actividad…',
    loadError: 'No pudimos cargar la actividad. Cierra y vuelve a abrir el panel.',
    unknownUser: 'Usuario desconocido',
  },
  access: {
    title: 'Acceso asesores',
    description:
      'Activa automatizaciones y define qué asesores pueden lanzarlas.',
    columns: {
      automation: 'Automatización',
      active: 'Activa',
      adminOnly: 'Solo admin',
      visibility: 'Asesores',
      advisors: 'Seleccionados',
      actions: 'Acciones',
    },
    save: 'Guardar',
    saving: 'Guardando…',
    visibility: {
      none: 'Ningún asesor',
      all: 'Todos los asesores',
      selected: 'Asesores seleccionados',
    },
    selectAdvisors: 'Asesores con acceso',
    selectAdvisorsPlaceholder: 'Elige uno o más asesores',
  },
  create: {
    title: 'Nueva automatización',
    titleEdit: 'Editar automatización',
    description:
      'Registra un proceso manual de n8n en el catálogo del portal. La ruta del webhook debe coincidir con el workflow.',
    descriptionEdit:
      'Modifica la definición de la automatización. Los cambios aplican al próximo lanzamiento.',
    fields: {
      slug: 'Identificador',
      title: 'Título',
      description: 'Descripción',
      webhookPath: 'Ruta del webhook',
      icon: 'Icono',
      advisorVisibility: 'Visibilidad para asesores',
      isActive: 'Activa al guardar',
      adminOnly: 'Solo administración',
      inputFields: 'Parámetros de entrada',
    },
    placeholders: {
      title: 'Sincronizar partners Odoo',
      description: 'Relanza la sincronización manual de contactos con Odoo.',
    },
    hints: {
      slug: 'Minúsculas, números y guiones. Se usa en logs y payloads.',
      webhookPath: 'Ruta relativa en n8n, sin dominio (ej. /webhook/sync-odoo-partners).',
      inputFields:
        'Parámetros que se piden al lanzar y viajan al webhook con su clave (select o texto libre).',
      inputKey: 'Clave para el payload: minúsculas, números y _ (ej. mes).',
    },
    inputFieldsEditor: {
      addField: 'Añadir parámetro',
      addSelectField: 'Añadir select',
      addTextField: 'Añadir texto',
      removeField: 'Quitar parámetro',
      type: 'Tipo',
      typeSelect: 'Select',
      typeText: 'Texto',
      key: 'Clave',
      label: 'Etiqueta',
      required: 'Obligatorio',
      defaultValue: 'Opción por defecto',
      defaultTextValue: 'Valor por defecto',
      defaultTextPlaceholder: 'Opcional',
      noDefault: 'Sin valor por defecto',
      options: 'Opciones',
      optionValue: 'Valor',
      optionLabel: 'Etiqueta',
      addOption: 'Añadir opción',
      removeOption: 'Quitar opción',
      empty: 'Sin parámetros: el webhook se lanza directamente.',
    },
    icons: {
      workflow: 'Flujo',
      refresh: 'Actualizar',
      database: 'Base de datos',
      users: 'Usuarios',
    },
    actions: {
      cancel: 'Cancelar',
      submit: 'Crear automatización',
      submitting: 'Creando…',
      submitEdit: 'Guardar cambios',
      submittingEdit: 'Guardando…',
    },
  },
  impuestoSociedadesConfig: {
    eyebrow: 'Operaciones',
    title: 'Configuración Impuesto sobre Sociedades',
    backLink: 'Volver a automatizaciones',
    addButton: 'Añadir configuración',
    notConfiguredTitle: 'Supabase no configurado',
    notConfiguredDescription:
      'Falta SUPABASE_SERVICE_ROLE_KEY en el entorno del portal.',
    emptyTitle: 'Sin configuraciones',
    emptyDescription:
      'Añade el primer ejercicio y tipo de empresa para alimentar los flujos de n8n.',
    filterAllYears: 'Todos los ejercicios',
    filterYear: 'Ejercicio {year}',
    filterGroupLabel: 'Filtrar por ejercicio',
    columns: {
      anio: 'Ejercicio',
      tipoEmpresa: 'Tipo de empresa',
      gravamen: 'Gravamen',
      actions: 'Acciones',
    },
    tipoEmpresa: {
      general: 'Régimen general',
      micropymes: 'Régimen de micropymes',
      reducida_dimension: 'Reducida dimensión',
      nueva_creacion: 'Nueva creación',
      emergentes: 'Entidades emergentes',
      patrimonial: 'Entidades patrimoniales',
    },
    drawer: {
      titleCreate: 'Nueva configuración',
      titleEdit: 'Editar configuración',
      description:
        'Define el tipo impositivo para un ejercicio y régimen. Solo puede haber un registro por combinación.',
      fields: {
        anio: 'Ejercicio fiscal',
        tipoEmpresa: 'Tipo de empresa',
        esEscala: 'Usa escala de gravamen',
        tipoGravamenFijo: 'Tipo de gravamen fijo (%)',
        baseGravamen: 'Base de gravamen (€)',
        tipoGravamenBase: 'Tipo sobre la base (%)',
        tipoGravamenRestante: 'Tipo sobre el resto (%)',
      },
      hints: {
        esEscala:
          'Actívalo para regímenes con tramos (p. ej. micropymes). Si no, indica un tipo fijo.',
        tipoGravamenFijo: 'Porcentaje único aplicable a toda la base.',
        baseGravamen: 'Importe hasta el que aplica el primer tipo.',
      },
      actions: {
        cancel: 'Cancelar',
        submitCreate: 'Crear configuración',
        submitEdit: 'Guardar cambios',
        submittingCreate: 'Creando…',
        submittingEdit: 'Guardando…',
      },
    },
    confirmDeleteTitle: 'Eliminar configuración',
    confirmDelete:
      'Se eliminará esta configuración del ejercicio. Los flujos de n8n dejarán de encontrarla. ¿Continuar?',
    confirmDeleteConfirm: 'Eliminar',
    edit: 'Editar',
    delete: 'Eliminar',
    toast: {
      created: 'Configuración creada',
      createFailed: 'No se pudo crear la configuración',
      updated: 'Configuración actualizada',
      updateFailed: 'No se pudo actualizar la configuración',
      deleted: 'Configuración eliminada',
      deleteFailed: 'No se pudo eliminar la configuración',
      loadFailed: 'No se pudo cargar la configuración',
    },
  },
} as const
