export const clientDocuments = {
  pageTitle: 'Documentos',
  pageDescription: 'Consulta, descarga y sube los archivos de tu asesoría.',
  rootBreadcrumb: 'Inicio',
  searchPlaceholder: 'Buscar en esta carpeta',
  upload: 'Subir archivos',
  refresh: 'Actualizar',
  refreshing: 'Actualizando…',
  viewGrid: 'Vista cuadrícula',
  viewList: 'Vista lista',
  viewModeLabel: 'Vista',
  loading: 'Cargando documentos…',
  loadingLabel: 'Cargando',
  emptyTitle: 'Esta carpeta está vacía',
  emptyDescription: 'Sube archivos para empezar.',
  emptyAction: 'Subir archivos',
  openFolder: 'Abrir carpeta',
  preview: 'Previsualizar',
  previewUnsupportedFormat:
    'El previsualizador aún no está preparado para este formato. Descarga el archivo desde el listado si lo necesitas.',
  previewTooLarge:
    'El archivo es demasiado grande para previsualizarlo. Descarga el archivo desde el listado.',
  download: 'Descargar',
  dropOverlayTitle: 'Arrastra archivos aquí',
  dropOverlayHint: 'Los archivos se guardarán en la carpeta actual',
  dropOverlayReleaseTitle: 'Suelta para subir',
  dropOverlayReleaseHint: 'Los archivos se guardarán en esta carpeta',
  dropOverlayUploadingTitle: 'Subiendo archivos…',
  dropOverlayUploadingHint: 'No cierres esta ventana hasta que termine.',
  dropOverlaySuccessTitle: 'Archivos subidos',
  dropOverlaySuccessHint: 'Ya están disponibles en esta carpeta.',
  openFolderHint: 'Doble clic para abrir carpeta',
  openFileHint: 'Doble clic para abrir',
  uploading: 'Subiendo…',
  downloading: 'Descargando…',
  saving: 'Guardando…',
  dropzoneTitle: 'Arrastra archivos aquí',
  dropzoneHint: 'o haz clic para seleccionarlos',
  duplicateTitle: 'Este archivo ya existe',
  duplicateSelectionTitle: 'Hay archivos repetidos',
  duplicateFileLabel: 'Archivo',
  duplicateLocationLabel: 'Ya está guardado en',
  duplicateHint: 'No se ha subido nada. Cambia el nombre del archivo o déjalo como está si ya lo tienes.',
  duplicateSelectionHint:
    'Has seleccionado dos archivos con el mismo nombre. No se ha subido ninguno: renombra uno de ellos e inténtalo de nuevo.',
  duplicateDismiss: 'Entendido',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  create: 'Crear',
  save: 'Guardar',
  retry: 'Reintentar',
  modified: 'Modificado',
  folderLabel: 'Carpeta',
  demoBannerTitle: 'Vista de demostración',
  demoBannerDescription:
    'Estás explorando datos de ejemplo. Puedes navegar, subir y descargar archivos para probar la experiencia.',
  demoActionDisabled: 'No disponible en la vista de demostración.',
  shortcuts: {
    refresh: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
    upload: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
    toggleView: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
  },
} as const
