export const clientDocuments = {
  pageTitle: 'Documentos',
  pageDescription: 'Consulta, sube y organiza los archivos de tu asesoría.',
  rootBreadcrumb: 'Inicio',
  searchPlaceholder: 'Buscar en esta carpeta',
  upload: 'Subir archivos',
  newFolder: 'Nueva carpeta',
  refresh: 'Actualizar',
  refreshing: 'Actualizando…',
  viewGrid: 'Vista cuadrícula',
  viewList: 'Vista lista',
  viewModeLabel: 'Vista',
  loading: 'Cargando documentos…',
  loadingLabel: 'Cargando',
  emptyTitle: 'Esta carpeta está vacía',
  emptyDescription: 'Sube archivos o crea una carpeta para empezar.',
  emptyAction: 'Subir archivos',
  openFolder: 'Abrir carpeta',
  preview: 'Previsualizar',
  previewUnsupportedFormat:
    'El previsualizador aún no está preparado para este formato. Descarga el archivo desde el listado si lo necesitas.',
  previewTooLarge:
    'El archivo es demasiado grande para previsualizarlo. Descarga el archivo desde el listado.',
  download: 'Descargar',
  rename: 'Renombrar',
  delete: 'Eliminar',
  move: 'Mover',
  moveTitle: 'Mover elemento',
  moveDescription: 'Elige la carpeta de destino.',
  moveHere: 'Mover aquí',
  moveToFolder: 'Mover a «{name}»',
  dropOverlayTitle: 'Arrastra archivos aquí',
  dropOverlayHint: 'Los archivos se guardarán en la carpeta actual',
  dropOverlayReleaseTitle: 'Suelta para subir',
  dropOverlayReleaseHint: 'Los archivos se guardarán en esta carpeta',
  dropOverlayUploadingTitle: 'Subiendo archivos…',
  dropOverlayUploadingHint: 'No cierres esta ventana hasta que termine.',
  dropOverlaySuccessTitle: 'Archivos subidos',
  dropOverlaySuccessHint: 'Ya están disponibles en esta carpeta.',
  dropOnFolder: 'Suelta para subir a esta carpeta',
  dropInternalHint: 'Suelta para mover aquí',
  openFolderHint: 'Doble clic para abrir carpeta',
  openFileHint: 'Doble clic para abrir',
  moreActions: 'Más acciones',
  uploading: 'Subiendo…',
  downloading: 'Descargando…',
  deleting: 'Eliminando…',
  saving: 'Guardando…',
  dropzoneTitle: 'Arrastra archivos aquí',
  dropzoneHint: 'o haz clic para seleccionarlos',
  newFolderTitle: 'Nueva carpeta',
  newFolderLabel: 'Nombre de la carpeta',
  newFolderPlaceholder: 'Ej. Facturas 2026',
  renameTitle: 'Renombrar',
  renameLabel: 'Nuevo nombre',
  deleteTitle: 'Eliminar elemento',
  deleteDescription:
    '¿Seguro que quieres enviar «{name}» a la papelera? Podrás recuperarlo desde Google Drive si lo necesitas.',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  confirmDelete: 'Eliminar',
  create: 'Crear',
  save: 'Guardar',
  retry: 'Reintentar',
  modified: 'Modificado',
  folderLabel: 'Carpeta',
  demoBannerTitle: 'Vista de demostración',
  demoBannerDescription:
    'Estás explorando datos de ejemplo. Puedes navegar, subir, renombrar y eliminar archivos para probar la experiencia.',
  demoActionDisabled: 'No disponible en la vista de demostración.',
  shortcuts: {
    refresh: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
    upload: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
    newFolder: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
    toggleView: {
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
  },
  errors: {
    forbidden: 'No tienes permiso para acceder a estos documentos.',
    not_linked:
      'Tu espacio de documentos aún no está configurado. Contacta con tu asesoría.',
    not_found: 'No encontramos el elemento solicitado.',
    drive_unavailable:
      'No pudimos acceder a tus documentos. Inténtalo de nuevo en unos minutos.',
    name_conflict: 'Ya existe un elemento con ese nombre en esta carpeta.',
    too_large: 'El archivo supera el tamaño máximo permitido.',
    invalid_name: 'El nombre no es válido. Evita caracteres especiales.',
    upload_failed: 'No pudimos subir uno o más archivos.',
  },
  states: {
    notLinked: {
      title: 'Documentos no disponibles',
      description:
        'Tu espacio de documentos aún no está configurado. Contacta con tu asesoría para activarlo.',
    },
    forbidden: {
      title: 'Acceso restringido',
      description: 'No tienes permiso para ver esta sección.',
    },
    driveUnavailable: {
      title: 'No pudimos cargar tus documentos',
      description:
        'El servicio de documentos no está disponible en este momento. Inténtalo de nuevo.',
    },
  },
} as const
