export const colaboradores = {
  title: 'Colaboradores',
  description:
    'Da acceso limitado al portal a personas de tu equipo. Cada colaborador solo ve las secciones que le habilites.',
  enableLabel: 'Activar colaboradores',
  enableHint: 'Desactivado por defecto. Actívalo para poder invitar colaboradores.',
  limitReached: 'Has alcanzado el límite de colaboradores ({max}).',
  addButton: 'Invitar colaborador',
  emptyTitle: 'Sin colaboradores todavía',
  emptyDescription: 'Cuando invites a alguien de tu equipo, aparecerá en esta lista.',
  columns: {
    name: 'Nombre',
    email: 'Correo',
    sections: 'Acceso',
    status: 'Estado',
  },
  status: {
    active: 'Activo',
    invited: 'Invitado',
    disabled: 'Desactivado',
  },
  sections: {
    '/obligaciones': 'Obligaciones',
    '/tramites': 'Trámites',
    '/documentos': 'Documentos',
    '/firmas': 'Firmas',
    '/guias': 'Guías',
  },
  form: {
    createTitle: 'Invitar colaborador',
    editTitle: 'Editar colaborador',
    personalDataLabel: 'Datos del colaborador',
    firstName: 'Nombre',
    firstSurname: 'Primer apellido',
    secondSurname: 'Segundo apellido',
    email: 'Correo electrónico',
    sectionsLabel: 'Acceso por sección',
    templatesLabel: 'Plantilla de rol',
    templatesHint: 'Elige un punto de partida; podrás ajustar cada sección a mano después.',
    templates: {
      contable: 'Contable',
      documental: 'Documental',
      firmante: 'Firmante',
      completo: 'Colaborador completo',
      consulta: 'Solo consulta',
    },
    levels: {
      none: 'Sin acceso',
      read: 'Ver',
      write: 'Gestionar',
    },
    statusGroupLabel: 'Estado del acceso',
    isEnabledLabel: 'Acceso activo',
    save: 'Guardar',
    saving: 'Guardando…',
    create: 'Enviar invitación',
    creating: 'Enviando…',
    cancel: 'Cancelar',
    domainMismatch:
      'Este correo no pertenece al dominio de tu propia cuenta ({domain}). ¿Seguro que quieres continuar?',
    successCreate: 'Colaborador invitado. Se ha enviado la invitación por correo.',
    successUpdate: 'Colaborador actualizado.',
    successDelete: 'Colaborador eliminado.',
    successActivate: 'Colaborador activado.',
    successDeactivate: 'Colaborador desactivado.',
    activateButton: 'Activar',
    deactivateButton: 'Desactivar',
    editAriaLabel: 'Editar colaborador',
    deleteAriaLabel: 'Eliminar colaborador',
    confirmDelete: '¿Seguro que quieres eliminar a este colaborador?',
    errors: {
      forbidden: 'No tienes permiso para hacer esto.',
      feature_disabled: 'Activa primero la funcionalidad de colaboradores.',
      limit_reached: 'Has alcanzado el límite de colaboradores.',
      duplicate_email: 'Ya existe una cuenta con ese correo.',
      create_failed: 'No se pudo crear el colaborador. Inténtalo de nuevo.',
      not_found: 'No se ha encontrado el colaborador.',
      validation: 'Revisa los datos del formulario.',
    },
  },
} as const
