export const portalChatter = {
  title: 'Conversación',
  tabConversation: 'Conversación',
  loading: 'Cargando mensajes…',
  loadingOlder: 'Cargando mensajes anteriores…',
  empty: 'Todavía no hay mensajes en este trámite.',
  composerPlaceholder: 'Escribe un mensaje…',
  formatBold: 'Negrita',
  formatItalic: 'Cursiva',
  formatUnderline: 'Subrayado',
  formatBulletList: 'Lista con viñetas',
  formatOrderedList: 'Lista numerada',
  composerEmpty: 'Mensaje vacío',
  composerHasContent: 'Mensaje con contenido',
  sendButton: 'Enviar',
  sending: 'Enviando…',
  readOnlyClosedTicket:
    'Esta consulta está cerrada. Puedes leer el historial, pero no enviar mensajes nuevos.',
  youLabel: 'Tú',
  authorAvatarAlt: 'Foto de {name}',
  authorAvatarLoading: 'Cargando foto de {name}',
  replyAction: 'Responder',
  replyingTo: 'Respondiendo a {name}',
  cancelReply: 'Cancelar respuesta',
  attachmentsLabel: 'Adjuntos',
  previewAttachment: 'Previsualizar: {name}',
  openInDocuments: 'Ver en documentos: {name}',
  attachFile: 'Adjuntar archivo',
  removeAttachment: 'Quitar {name}',
  uploading: 'Subiendo…',
  mockBadge: 'Vista de prueba (sin Odoo)',
  errors: {
    forbidden: 'No tienes permiso para ver esta conversación.',
    not_linked: 'Tu cuenta no está vinculada. Contacta con tu asesor para activarla.',
    not_found: 'No encontramos el trámite solicitado.',
    odoo_unavailable: 'No pudimos acceder a la conversación. Inténtalo de nuevo.',
    odoo_rate_limited:
      'El servidor está recibiendo mucha demanda. Vuelve a intentarlo en unos minutos.',
    invalid_body: 'El mensaje debe tener entre 1 y 2000 caracteres.',
    read_only: 'No puedes enviar mensajes en este trámite.',
    invalid_parent: 'No pudimos responder a ese mensaje.',
    invalid_attachment: 'El archivo no tiene un formato permitido.',
    attachment_too_large: 'El archivo supera el tamaño máximo permitido.',
    too_many_attachments: 'Puedes adjuntar como máximo 5 archivos por mensaje.',
  },
} as const
