export const profile = {
  pageTitle: 'Perfil',
  pageDescription:
    'Consulta tus datos de contacto y fiscales. Los cambios se solicitan a tu gestor y no se aplican al instante.',
  requestModeHint:
    'Modifica solo los datos que necesites. Enviaremos únicamente los campos que hayan cambiado.',
  sections: {
    personal: 'Datos personales',
    address: 'Dirección fiscal',
  },
  labels: {
    name: 'Nombre',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    addressLine1: 'Calle y número',
    addressLine2: 'Piso, puerta (opcional)',
    postalCode: 'Código postal',
    city: 'Municipio',
    province: 'Provincia',
    country: 'País',
    taxId: 'NIF/CIF',
    iban: 'IBAN',
    changeField: 'Quiero cambiar este dato',
    currentValue: 'Valor actual',
    newValue: 'Nuevo valor',
  },
  actions: {
    requestChange: 'Solicitar cambio de datos',
    submitRequest: 'Enviar solicitud',
    cancel: 'Cancelar',
  },
  emptyPhone: 'No indicado',
  successTitle: '¡Todo listo por aquí!',
  successMessage: 'Tu gestor ya está revisando tu perfil. Te avisaremos en cuanto esté todo actualizado. 😉',
  successDismiss: 'Estupendo',
  errors: {
    unauthorized: 'Debes iniciar sesión para solicitar cambios.',
    forbidden: 'Esta sección solo está disponible para clientes.',
    no_changes: 'No has modificado ningún dato. Cambia al menos un campo antes de enviar.',
    name: 'El nombre es obligatorio.',
    unknown: 'No pudimos enviar la solicitud. Inténtalo de nuevo.',
    email: 'Introduce un correo electrónico válido.',
    phone: 'Introduce un teléfono válido.',
    taxId: 'Introduce un NIF, NIE o CIF válido.',
    iban: 'Introduce un IBAN válido.',
    addressLine1: 'La calle y número son obligatorios.',
    postalCode: 'Introduce un código postal de 5 dígitos.',
    city: 'El municipio es obligatorio.',
    province: 'La provincia es obligatoria.',
    country: 'El país es obligatorio.',
  },
} as const
