/**
 * Catálogo de Ocupaciones SEPE (CNO-2011), usado en el campo "Seleccionar ocupación del SEPE"
 * del wizard de alta de trabajador. Extraído de OCUPACIONES.pdf (listado oficial de
 * "Comunicación de Contratos"); las 15 descripciones que quedaron truncadas a mitad de
 * frase por una limitación del PDF original se completaron contra el listado oficial
 * CNO-2011 del INE (ine.es/daco/daco42/clasificaciones/cno11_notas.pdf).
 */
export type SepeOcupacion = {
  code: string
  label: string
}

export const SEPE_OCUPACIONES: SepeOcupacion[] = [
  { code: '0011', label: 'Oficiales de las fuerzas armadas' },
  { code: '0012', label: 'Suboficiales de las fuerzas armadas' },
  { code: '0020', label: 'Tropa y marinería de las fuerzas armadas' },
  { code: '1111', label: 'Miembros del poder ejecutivo (nacional, autonómico y local) y del poder legislativo' },
  { code: '1112', label: 'Personal directivo de la Administración Pública' },
  { code: '1113', label: 'Directores de organizaciones de interés social' },
  { code: '1120', label: 'Directores generales y presidentes ejecutivos' },
  { code: '1211', label: 'Directores financieros' },
  { code: '1212', label: 'Directores de recursos humanos' },
  { code: '1219', label: 'Directores de políticas y planificación y de otros departamentos administrativos no clasificados bajo otros epígrafes' },
  { code: '1221', label: 'Directores comerciales y de ventas' },
  { code: '1222', label: 'Directores de publicidad y relaciones públicas' },
  { code: '1223', label: 'Directores de investigación y desarrollo' },
  { code: '1311', label: 'Directores de producción de explotaciones agropecuarias y forestales' },
  { code: '1312', label: 'Directores de producción de explotaciones pesqueras y acuícolas' },
  { code: '1313', label: 'Directores de industrias manufactureras' },
  { code: '1314', label: 'Directores de explotaciones mineras' },
  { code: '1315', label: 'Directores de empresas de abastecimiento, transporte, distribución y afines' },
  { code: '1316', label: 'Directores de empresas de construcción' },
  { code: '1321', label: 'Directores de servicios de tecnologías de la información y las comunicaciones (TIC)' },
  { code: '1322', label: 'Directores de servicios sociales para niños' },
  { code: '1323', label: 'Directores-gerentes de centros sanitarios' },
  { code: '1324', label: 'Directores de servicios sociales para personas mayores' },
  { code: '1325', label: 'Directores de otros servicios sociales' },
  { code: '1326', label: 'Directores de servicios de educación' },
  { code: '1327', label: 'Directores de sucursales de bancos, de servicios financieros y de seguros' },
  { code: '1329', label: 'Directores de otras empresas de servicios profesionales no clasificados bajo otros epígrafes' },
  { code: '1411', label: 'Directores y gerentes de hoteles' },
  { code: '1419', label: 'Directores y gerentes de otras empresas de servicios de alojamiento' },
  { code: '1421', label: 'Directores y gerentes de restaurantes' },
  { code: '1422', label: 'Directores y gerentes de bares, cafeterías y similares' },
  { code: '1429', label: 'Directores y gerentes de empresas de catering y otras empresas de restauración' },
  { code: '1431', label: 'Directores y gerentes de empresas de comercio al por mayor' },
  { code: '1432', label: 'Directores y gerentes de empresas de comercio al por menor' },
  { code: '1501', label: 'Directores y gerentes de empresas de actividades recreativas, culturales y deportivas' },
  { code: '1509', label: 'Directores y gerentes de empresas de gestión de residuos y de otras empresas de servicios no clasificados bajo otros epígrafes' },
  { code: '2111', label: 'Médicos de familia' },
  { code: '2112', label: 'Otros médicos especialistas' },
  { code: '2121', label: 'Enfermeros no especializados' },
  { code: '2122', label: 'Enfermeros especializados (excepto matronos)' },
  { code: '2123', label: 'Matronos' },
  { code: '2130', label: 'Veterinarios' },
  { code: '2140', label: 'Farmacéuticos' },
  { code: '2151', label: 'Odontólogos y estomatólogos' },
  { code: '2152', label: 'Fisioterapeutas' },
  { code: '2153', label: 'Dietistas y nutricionistas' },
  { code: '2154', label: 'Logopedas' },
  { code: '2155', label: 'Ópticos-optometristas' },
  { code: '2156', label: 'Terapeutas ocupacionales' },
  { code: '2157', label: 'Podólogos' },
  { code: '2158', label: 'Profesionales de la salud y la higiene laboral y ambiental' },
  { code: '2159', label: 'Profesionales de la salud no clasificados bajo otros epígrafes' },
  { code: '2210', label: 'Profesores de universidades y otra enseñanza superior (excepto formación profesional)' },
  { code: '2220', label: 'Profesores de formación profesional (materias específicas)' },
  { code: '2230', label: 'Profesores de enseñanza secundaria (excepto materias específicas de formación profesional)' },
  { code: '2240', label: 'Profesores de enseñanza primaria' },
  { code: '2251', label: 'Maestros de educación infantil' },
  { code: '2252', label: 'Técnicos en educación infantil' },
  { code: '2311', label: 'Profesores de educación especial' },
  { code: '2312', label: 'Técnicos educadores de educación especial' },
  { code: '2321', label: 'Especialistas en métodos didácticos y pedagógicos' },
  { code: '2322', label: 'Profesores de enseñanza no reglada de idiomas' },
  { code: '2323', label: 'Profesores de enseñanza no reglada de música y danza' },
  { code: '2324', label: 'Profesores de enseñanza no reglada de artes' },
  { code: '2325', label: 'Instructores en tecnologías de la información en enseñanza no reglada' },
  { code: '2326', label: 'Profesionales de la educación ambiental' },
  { code: '2329', label: 'Profesores y profesionales de la enseñanza no clasificados bajo otros epígrafes' },
  { code: '2411', label: 'Físicos y astrónomos' },
  { code: '2412', label: 'Meteorólogos' },
  { code: '2413', label: 'Químicos' },
  { code: '2414', label: 'Geólogos y geofísicos' },
  { code: '2415', label: 'Matemáticos y actuarios' },
  { code: '2416', label: 'Estadísticos' },
  { code: '2421', label: 'Biólogos, botánicos, zoólogos y afines' },
  { code: '2422', label: 'Ingenieros agrónomos' },
  { code: '2423', label: 'Ingenieros de montes' },
  { code: '2424', label: 'Ingenieros técnicos agrícolas' },
  { code: '2425', label: 'Ingenieros técnicos forestales y del medio natural' },
  { code: '2426', label: 'Profesionales de la protección ambiental' },
  { code: '2427', label: 'Enólogos' },
  { code: '2431', label: 'Ingenieros industriales y de producción' },
  { code: '2432', label: 'Ingenieros en construcción y obra civil' },
  { code: '2433', label: 'Ingenieros mecánicos' },
  { code: '2434', label: 'Ingenieros aeronáuticos' },
  { code: '2435', label: 'Ingenieros químicos' },
  { code: '2436', label: 'Ingenieros de minas, metalúrgicos y afines' },
  { code: '2437', label: 'Ingenieros ambientales' },
  { code: '2439', label: 'Ingenieros no clasificados bajo otros epígrafes' },
  { code: '2441', label: 'Ingenieros en electricidad' },
  { code: '2442', label: 'Ingenieros electrónicos' },
  { code: '2443', label: 'Ingenieros en telecomunicaciones' },
  { code: '2451', label: 'Arquitectos (excepto arquitectos paisajistas y urbanistas)' },
  { code: '2452', label: 'Arquitectos paisajistas' },
  { code: '2453', label: 'Urbanistas e ingenieros de tráfico' },
  { code: '2454', label: 'Ingenieros geógrafos y cartógrafos' },
  { code: '2461', label: 'Ingenieros técnicos industriales y de producción' },
  { code: '2462', label: 'Ingenieros técnicos de obras públicas' },
  { code: '2463', label: 'Ingenieros técnicos mecánicos' },
  { code: '2464', label: 'Ingenieros técnicos aeronáuticos' },
  { code: '2465', label: 'Ingenieros técnicos químicos' },
  { code: '2466', label: 'Ingenieros técnicos de minas, metalúrgicos y afines' },
  { code: '2469', label: 'Ingenieros técnicos no clasificados bajo otros epígrafes' },
  { code: '2471', label: 'Ingenieros técnicos en electricidad' },
  { code: '2472', label: 'Ingenieros técnicos en electrónica' },
  { code: '2473', label: 'Ingenieros técnicos en telecomunicaciones' },
  { code: '2481', label: 'Arquitectos técnicos y técnicos urbanistas' },
  { code: '2482', label: 'Diseñadores de productos y de prendas' },
  { code: '2483', label: 'Ingenieros técnicos en topografía' },
  { code: '2484', label: 'Diseñadores gráficos y multimedia' },
  { code: '2511', label: 'Abogados' },
  { code: '2512', label: 'Fiscales' },
  { code: '2513', label: 'Jueces y magistrados' },
  { code: '2591', label: 'Notarios y registradores' },
  { code: '2592', label: 'Procuradores' },
  { code: '2599', label: 'Profesionales del derecho no clasificados bajo otros epígrafes' },
  { code: '2611', label: 'Especialistas en contabilidad' },
  { code: '2612', label: 'Asesores financieros y en inversiones' },
  { code: '2613', label: 'Analistas financieros' },
  { code: '2621', label: 'Analistas de gestión y organización' },
  { code: '2622', label: 'Especialistas en administración de política de empresas' },
  { code: '2623', label: 'Especialistas de la Administración Pública' },
  { code: '2624', label: 'Especialistas en políticas y servicios de personal y afines' },
  { code: '2625', label: 'Especialistas en formación de personal' },
  { code: '2630', label: 'Técnicos de empresas y actividades turísticas' },
  { code: '2640', label: 'Profesionales de ventas técnicas y médicas (excepto las TIC)' },
  { code: '2651', label: 'Profesionales de la publicidad y la comercialización' },
  { code: '2652', label: 'Profesionales de relaciones públicas' },
  { code: '2653', label: 'Profesionales de la venta de tecnologías de la información y las comunicaciones' },
  { code: '2711', label: 'Analistas de sistemas' },
  { code: '2712', label: 'Analistas y diseñadores de software' },
  { code: '2713', label: 'Analistas, programadores y diseñadores web y multimedia' },
  { code: '2719', label: 'Analistas y diseñadores de software y multimedia no clasificados bajo otros epígrafes' },
  { code: '2721', label: 'Diseñadores y administradores de bases de datos' },
  { code: '2722', label: 'Administradores de sistemas y redes' },
  { code: '2723', label: 'Analistas de redes informáticas' },
  { code: '2729', label: 'Especialistas en bases de datos y en redes informáticas no clasificados bajo otros epígrafes' },
  { code: '2810', label: 'Economistas' },
  { code: '2821', label: 'Sociólogos, geógrafos, antropólogos, arqueólogos y afines' },
  { code: '2822', label: 'Filósofos, historiadores y profesionales en ciencias políticas' },
  { code: '2823', label: 'Psicólogos' },
  { code: '2824', label: 'Profesionales del trabajo y la educación social' },
  { code: '2825', label: 'Agentes de igualdad de oportunidades entre mujeres y hombres' },
  { code: '2830', label: 'Sacerdotes de las distintas religiones' },
  { code: '2911', label: 'Archivistas y conservadores de museos' },
  { code: '2912', label: 'Bibliotecarios, documentalistas y afines' },
  { code: '2921', label: 'Escritores' },
  { code: '2922', label: 'Periodistas' },
  { code: '2923', label: 'Filólogos, intérpretes y traductores' },
  { code: '2931', label: 'Artistas de artes plásticas y visuales' },
  { code: '2932', label: 'Compositores, músicos y cantantes' },
  { code: '2933', label: 'Coreógrafos y bailarines' },
  { code: '2934', label: 'Directores de cine, de teatro y afines' },
  { code: '2935', label: 'Actores' },
  { code: '2936', label: 'Locutores de radio, televisión y otros presentadores' },
  { code: '2937', label: 'Profesionales de espectáculos taurinos' },
  { code: '2939', label: 'Artistas creativos e interpretativos no clasificados bajo otros epígrafes' },
  { code: '3110', label: 'Delineantes y dibujantes técnicos' },
  { code: '3121', label: 'Técnicos en ciencias físicas y químicas' },
  { code: '3122', label: 'Técnicos en construcción' },
  { code: '3123', label: 'Técnicos en electricidad' },
  { code: '3124', label: 'Técnicos en electrónica (excepto electro medicina)' },
  { code: '3125', label: 'Técnicos en electrónica, especialidad en electro medicina' },
  { code: '3126', label: 'Técnicos en mecánica' },
  { code: '3127', label: 'Técnicos y analistas de laboratorio en química industrial' },
  { code: '3128', label: 'Técnicos en metalurgia y minas' },
  { code: '3129', label: 'Otros técnicos de las ciencias físicas, químicas, medioambientales y de las ingenierías' },
  { code: '3131', label: 'Técnicos en instalaciones de producción de energía' },
  { code: '3132', label: 'Técnicos en instalaciones de tratamiento de residuos, de aguas y otros operadores en plantas similares' },
  { code: '3133', label: 'Técnicos en control de instalaciones de procesamiento de productos químicos' },
  { code: '3134', label: 'Técnicos de refinerías de petróleo y gas natural' },
  { code: '3135', label: 'Técnicos en control de procesos de producción de metales' },
  { code: '3139', label: 'Técnicos en control de procesos no clasificados bajo otros epígrafes' },
  { code: '3141', label: 'Técnicos en ciencias biológicas (excepto en áreas sanitarias)' },
  { code: '3142', label: 'Técnicos agropecuarios' },
  { code: '3143', label: 'Técnicos forestales y del medio natural' },
  { code: '3151', label: 'Jefes y oficiales de máquinas' },
  { code: '3152', label: 'Capitanes y oficiales de puente' },
  { code: '3153', label: 'Pilotos de aviación y profesionales afines' },
  { code: '3154', label: 'Controladores de tráfico aéreo' },
  { code: '3155', label: 'Técnicos en seguridad aeronáutica' },
  { code: '3160', label: 'Técnicos de control de calidad de las ciencias físicas, químicas y de las ingenierías' },
  { code: '3201', label: 'Supervisores en ingeniería de minas' },
  { code: '3202', label: 'Supervisores de la construcción' },
  { code: '3203', label: 'Supervisores de industrias alimenticias y del tabaco' },
  { code: '3204', label: 'Supervisores de industrias química y farmacéutica' },
  { code: '3205', label: 'Supervisores de industrias de transformación de plásticos, caucho y resinas naturales' },
  { code: '3206', label: 'Supervisores de industrias de la madera y pastero papeleras' },
  { code: '3207', label: 'Supervisores de la producción en industrias de artes gráficas y en la fabricación de productos' },
  { code: '3209', label: 'Supervisores de otras industrias manufactureras' },
  { code: '3311', label: 'Técnicos en radioterapia' },
  { code: '3312', label: 'Técnicos en imagen para el diagnóstico' },
  { code: '3313', label: 'Técnicos en anatomía patológica y citología' },
  { code: '3314', label: 'Técnicos en laboratorio de diagnóstico clínico' },
  { code: '3315', label: 'Técnicos en ortoprótesis' },
  { code: '3316', label: 'Técnicos en prótesis dentales' },
  { code: '3317', label: 'Técnicos en audioprótesis' },
  { code: '3321', label: 'Técnicos superiores en higiene bucodental' },
  { code: '3322', label: 'Técnicos superiores en documentación sanitaria' },
  { code: '3323', label: 'Técnicos superiores en dietética' },
  { code: '3324', label: 'Técnicos en optometría' },
  { code: '3325', label: 'Ayudantes fisioterapeutas' },
  { code: '3326', label: 'Técnicos en prevención de riesgos laborales y salud ambiental' },
  { code: '3327', label: 'Ayudantes de veterinaria' },
  { code: '3329', label: 'Técnicos de la sanidad no clasificados bajo otros epígrafes' },
  { code: '3331', label: 'Profesionales de la acupuntura, la naturopatía, la homeopatía, la medicina tradicional china y la ayurveda' },
  { code: '3339', label: 'Otros profesionales de las terapias alternativas' },
  { code: '3401', label: 'Profesionales de apoyo e intermediarios de cambio, bolsa y finanzas' },
  { code: '3402', label: 'Comerciales de préstamos y créditos' },
  { code: '3403', label: 'Tenedores de libros' },
  { code: '3404', label: 'Profesionales de apoyo en servicios estadísticos, matemáticos y afines' },
  { code: '3405', label: 'Tasadores' },
  { code: '3510', label: 'Agentes y representantes comerciales' },
  { code: '3521', label: 'Mediadores y agentes de seguros' },
  { code: '3522', label: 'Agentes de compras' },
  { code: '3523', label: 'Consignatarios' },
  { code: '3531', label: 'Representantes de aduanas' },
  { code: '3532', label: 'Organizadores de conferencias y eventos' },
  { code: '3533', label: 'Agentes o intermediarios en la contratación de la mano de obra (excepto representantes de espectáculos)' },
  { code: '3534', label: 'Agentes y administradores de la propiedad inmobiliaria' },
  { code: '3535', label: 'Portavoces y agentes de relaciones públicas' },
  { code: '3539', label: 'Representantes artísticos y deportivos y otros agentes de servicios comerciales no clasificados bajo otros epígrafes' },
  { code: '3611', label: 'Supervisores de secretaría' },
  { code: '3612', label: 'Asistentes jurídico-legales' },
  { code: '3613', label: 'Asistentes de dirección y administrativos' },
  { code: '3614', label: 'Secretarios de centros médicos o clínicas' },
  { code: '3621', label: 'Profesionales de apoyo de la Administración Pública de tributos' },
  { code: '3622', label: 'Profesionales de apoyo de la Administración Pública de servicios sociales' },
  { code: '3623', label: 'Profesionales de apoyo de la Administración Pública de servicios de expedición de licencias' },
  { code: '3629', label: 'Otros profesionales de apoyo de la Administración Pública para tareas de inspección y control y tareas similares' },
  { code: '3631', label: 'Técnicos de la policía nacional, autonómica y local' },
  { code: '3632', label: 'Suboficiales de la guardia civil' },
  { code: '3711', label: 'Profesionales de apoyo de servicios jurídicos y servicios similares' },
  { code: '3712', label: 'Detectives privados' },
  { code: '3713', label: 'Profesionales de apoyo al trabajo y a la educación social' },
  { code: '3714', label: 'Promotores de igualdad de oportunidades entre mujeres y hombres' },
  { code: '3715', label: 'Animadores comunitarios' },
  { code: '3716', label: 'Auxiliares laicos de las religiones' },
  { code: '3721', label: 'Atletas y deportistas' },
  { code: '3722', label: 'Entrenadores y árbitros de actividades deportivas' },
  { code: '3723', label: 'Instructores de actividades deportivas' },
  { code: '3724', label: 'Monitores de actividades recreativas y de entretenimiento' },
  { code: '3731', label: 'Fotógrafos' },
  { code: '3732', label: 'Diseñadores y decoradores de interior' },
  { code: '3733', label: 'Técnicos en galerías de arte, museos y bibliotecas' },
  { code: '3734', label: 'Chefs' },
  { code: '3739', label: 'Otros técnicos y profesionales de apoyo de actividades culturales y artísticas' },
  { code: '3811', label: 'Técnicos en operaciones de sistemas informáticos' },
  { code: '3812', label: 'Técnicos en asistencia al usuario de tecnologías de la información' },
  { code: '3813', label: 'Técnicos en redes' },
  { code: '3814', label: 'Técnicos de la Web' },
  { code: '3820', label: 'Programadores informáticos' },
  { code: '3831', label: 'Técnicos de grabación audiovisual' },
  { code: '3832', label: 'Técnicos de radiodifusión' },
  { code: '3833', label: 'Técnicos de ingeniería de las telecomunicaciones' },
  { code: '4111', label: 'Empleados de contabilidad' },
  { code: '4112', label: 'Empleados de control de personal y nóminas' },
  { code: '4113', label: 'Empleados de oficina de servicios estadísticos, financieros y bancarios' },
  { code: '4121', label: 'Empleados de control de abastecimientos e inventario' },
  { code: '4122', label: 'Empleados de oficina de servicios de apoyo a la producción' },
  { code: '4123', label: 'Empleados de logística y transporte de pasajeros y mercancías' },
  { code: '4210', label: 'Empleados de bibliotecas y archivos' },
  { code: '4221', label: 'Empleados de servicios de correos (excepto empleados de mostrador)' },
  { code: '4222', label: 'Codificadores y correctores de imprenta' },
  { code: '4223', label: 'Empleados de servicio de personal' },
  { code: '4301', label: 'Grabadores de datos' },
  { code: '4309', label: 'Empleados administrativos sin tareas de atención al público no clasificados bajo otros epígrafes' },
  { code: '4411', label: 'Empleados de información al usuario' },
  { code: '4412', label: 'Recepcionistas (excepto de hoteles)' },
  { code: '4421', label: 'Empleados de agencias de viajes' },
  { code: '4422', label: 'Recepcionistas de hoteles' },
  { code: '4423', label: 'Telefonistas' },
  { code: '4424', label: 'Teleoperadores' },
  { code: '4430', label: 'Agentes de encuestas' },
  { code: '4441', label: 'Cajeros de bancos y afines' },
  { code: '4442', label: 'Empleados de venta de apuestas' },
  { code: '4443', label: 'Empleados de sala de juegos y afines' },
  { code: '4444', label: 'Empleados de casas de empeño y de préstamos' },
  { code: '4445', label: 'Cobradores de facturas, deudas y empleados afines' },
  { code: '4446', label: 'Empleados de mostrador de correos' },
  { code: '4500', label: 'Empleados administrativos con tareas de atención al público no clasificados bajo otros epígrafes' },
  { code: '5000', label: 'Camareros y cocineros propietarios' },
  { code: '5110', label: 'Cocineros asalariados' },
  { code: '5120', label: 'Camareros asalariados' },
  { code: '5210', label: 'Jefes de sección de tiendas y almacenes' },
  { code: '5220', label: 'Vendedores en tiendas y almacenes' },
  { code: '5300', label: 'Comerciantes propietarios de tiendas' },
  { code: '5411', label: 'Vendedores en quioscos' },
  { code: '5412', label: 'Vendedores en mercados ocasionales y mercadillos' },
  { code: '5420', label: 'Operadores de telemarketing' },
  { code: '5430', label: 'Expendedores de gasolineras' },
  { code: '5491', label: 'Vendedores a domicilio' },
  { code: '5492', label: 'Promotores de venta' },
  { code: '5493', label: 'Modelos de moda, arte y publicidad' },
  { code: '5499', label: 'Vendedores no clasificados bajo otros epígrafes' },
  { code: '5500', label: 'Cajeros y taquilleros (excepto bancos)' },
  { code: '5611', label: 'Auxiliares de enfermería hospitalaria' },
  { code: '5612', label: 'Auxiliares de enfermería de atención primaria' },
  { code: '5621', label: 'Técnicos auxiliares de farmacia' },
  { code: '5622', label: 'Técnicos de emergencias sanitarias' },
  { code: '5629', label: 'Trabajadores de los cuidados a las personas en servicios de salud no clasificados bajo otros epígrafes' },
  { code: '5710', label: 'Trabajadores de los cuidados personales a domicilio' },
  { code: '5721', label: 'Cuidadores de niños en guarderías y centros educativos' },
  { code: '5722', label: 'Cuidadores de niños en domicilios' },
  { code: '5811', label: 'Peluqueros' },
  { code: '5812', label: 'Especialistas en tratamientos de estética, bienestar y afines' },
  { code: '5821', label: 'Auxiliares de vuelo y camareros de avión, barco y tren' },
  { code: '5822', label: 'Revisores y cobradores de transporte terrestre' },
  { code: '5823', label: 'Acompañantes turísticos' },
  { code: '5824', label: 'Azafatos de tierra' },
  { code: '5825', label: 'Guías de turismo' },
  { code: '5831', label: 'Supervisores de mantenimiento y limpieza en oficinas, hoteles y otros establecimientos' },
  { code: '5832', label: 'Mayordomos del servicio doméstico' },
  { code: '5833', label: 'Conserjes de edificios' },
  { code: '5840', label: 'Trabajadores propietarios de pequeños alojamientos' },
  { code: '5891', label: 'Asistentes personales o personas de compañía' },
  { code: '5892', label: 'Empleados de pompas fúnebres y embalsamadores' },
  { code: '5893', label: 'Cuidadores de animales y adiestradores' },
  { code: '5894', label: 'Instructores de autoescuela' },
  { code: '5895', label: 'Astrólogos, adivinadores y afines' },
  { code: '5899', label: 'Trabajadores de servicios personales no clasificados bajo otros epígrafes' },
  { code: '5910', label: 'Guardias civiles' },
  { code: '5921', label: 'Policías nacionales' },
  { code: '5922', label: 'Policías autonómicos' },
  { code: '5923', label: 'Policías locales' },
  { code: '5931', label: 'Bomberos (excepto forestales)' },
  { code: '5932', label: 'Bomberos forestales' },
  { code: '5941', label: 'Vigilantes de seguridad y similares habilitados para ir armados' },
  { code: '5942', label: 'Auxiliares de vigilante de seguridad y similares no habilitados para ir armados' },
  { code: '5991', label: 'Vigilantes de prisiones' },
  { code: '5992', label: 'Bañistas-socorristas' },
  { code: '5993', label: 'Agentes forestales y medioambientales' },
  { code: '5999', label: 'Trabajadores de los servicios de protección y seguridad no clasificados bajo otros epígrafes' },
  { code: '6110', label: 'Trabajadores cualificados en actividades agrícolas (excepto en huertas, invernaderos, viveros y jardines)' },
  { code: '6120', label: 'Trabajadores cualificados en huertas, invernaderos, viveros y jardines' },
  { code: '6201', label: 'Trabajadores cualificados en actividades ganaderas de vacuno' },
  { code: '6202', label: 'Trabajadores cualificados en actividades ganaderas de ovino y caprino' },
  { code: '6203', label: 'Trabajadores cualificados en actividades ganaderas de porcino' },
  { code: '6204', label: 'Trabajadores cualificados en apicultura y sericicultura' },
  { code: '6205', label: 'Trabajadores cualificados en la avicultura y la cunicultura' },
  { code: '6209', label: 'Trabajadores cualificados en actividades ganaderas no clasificados bajo otros epígrafes' },
  { code: '6300', label: 'Trabajadores cualificados en actividades agropecuarias mixtas' },
  { code: '6410', label: 'Trabajadores cualificados en actividades forestales y del medio natural' },
  { code: '6421', label: 'Trabajadores cualificados en la acuicultura' },
  { code: '6422', label: 'Pescadores de aguas costeras y aguas dulces' },
  { code: '6423', label: 'Pescadores de altura' },
  { code: '6430', label: 'Trabajadores cualificados en actividades cinegéticas' },
  { code: '7111', label: 'Encofradores y operarios de puesta en obra de hormigón' },
  { code: '7112', label: 'Montadores de prefabricados estructurales (sólo hormigón)' },
  { code: '7121', label: 'Albañiles' },
  { code: '7122', label: 'Canteros, tronzadores, labrantes y grabadores de piedras' },
  { code: '7131', label: 'Carpinteros (excepto ebanistas)' },
  { code: '7132', label: 'Instaladores de cerramientos metálicos y carpinteros metálicos (excepto montadores de estructuras metálicas)' },
  { code: '7191', label: 'Mantenedores de edificios' },
  { code: '7192', label: 'Instaladores de fachadas técnicas' },
  { code: '7193', label: 'Instaladores de sistemas de impermeabilización en edificios' },
  { code: '7199', label: 'Otros trabajadores de las obras estructurales de construcción no clasificados bajo otros epígrafes' },
  { code: '7211', label: 'Escayolistas' },
  { code: '7212', label: 'Aplicadores de revestimientos de pasta y mortero' },
  { code: '7221', label: 'Fontaneros' },
  { code: '7222', label: 'Montadores-instaladores de gas en edificios' },
  { code: '7223', label: 'Instaladores de conductos en obra pública' },
  { code: '7231', label: 'Pintores y empapeladores' },
  { code: '7232', label: 'Pintores en las industrias manufactureras' },
  { code: '7240', label: 'Soladores, colocadores de parquet y afines' },
  { code: '7250', label: 'Mecánicos-instaladores de refrigeración y climatización' },
  { code: '7291', label: 'Montadores de cubiertas' },
  { code: '7292', label: 'Instaladores de material aislante térmico y de insonorización' },
  { code: '7293', label: 'Cristaleros' },
  { code: '7294', label: 'Montadores-instaladores de placas de energía solar' },
  { code: '7295', label: 'Personal de limpieza de fachadas de edificios y chimeneas' },
  { code: '7311', label: 'Moldeadores y macheros' },
  { code: '7312', label: 'Soldadores y oxicortadores' },
  { code: '7313', label: 'Chapistas y caldereros' },
  { code: '7314', label: 'Montadores de estructuras metálicas' },
  { code: '7315', label: 'Montadores de estructuras cableadas y empalmadores de cables' },
  { code: '7321', label: 'Herreros y forjadores' },
  { code: '7322', label: 'Trabajadores de la fabricación de herramientas, mecánico-ajustadores, modelistas, matriceros y afines' },
  { code: '7323', label: 'Ajustadores y operadores de máquinas-herramienta' },
  { code: '7324', label: 'Pulidores de metales y afiladores de herramientas' },
  { code: '7401', label: 'Mecánicos y ajustadores de vehículos de motor' },
  { code: '7402', label: 'Mecánicos y ajustadores de motores de avión' },
  { code: '7403', label: 'Mecánicos y ajustadores de maquinaria agrícola e industrial' },
  { code: '7404', label: 'Mecánicos y ajustadores de maquinaria naval y ferroviaria' },
  { code: '7405', label: 'Reparadores de bicicletas y afines' },
  { code: '7510', label: 'Electricistas de la construcción y afines' },
  { code: '7521', label: 'Mecánicos y reparadores de equipos eléctricos' },
  { code: '7522', label: 'Instaladores y reparadores de líneas eléctricas' },
  { code: '7531', label: 'Mecánicos y reparadores de equipos electrónicos' },
  { code: '7532', label: 'Instaladores y reparadores en electro medicina' },
  { code: '7533', label: 'Instaladores y reparadores en tecnologías de la información y las comunicaciones' },
  { code: '7611', label: 'Relojeros y mecánicos de instrumentos de precisión' },
  { code: '7612', label: 'Lutieres y similares; afinadores de instrumentos musicales' },
  { code: '7613', label: 'Joyeros, orfebres y plateros' },
  { code: '7614', label: 'Trabajadores de la cerámica, alfareros y afines' },
  { code: '7615', label: 'Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio' },
  { code: '7616', label: 'Rotulistas, grabadores de vidrio, pintores decorativos de artículos diversos' },
  { code: '7617', label: 'Artesanos en madera y materiales similares; cesteros, bruceros y trabajadores afines' },
  { code: '7618', label: 'Artesanos en tejidos, cueros y materiales similares, preparadores de fibra y tejedores con telares artesanos o de tejidos de punto y afines' },
  { code: '7619', label: 'Artesanos no clasificados bajo otros epígrafes' },
  { code: '7621', label: 'Trabajadores de procesos de preimpresión' },
  { code: '7622', label: 'Trabajadores de procesos de impresión' },
  { code: '7623', label: 'Trabajadores de procesos de encuadernación' },
  { code: '7701', label: 'Matarifes y trabajadores de las industrias cárnicas' },
  { code: '7702', label: 'Trabajadores de las industrias del pescado' },
  { code: '7703', label: 'Panaderos, pasteleros y confiteros' },
  { code: '7704', label: 'Trabajadores del tratamiento de la leche y elaboración de productos lácteos (incluidos helados)' },
  { code: '7705', label: 'Trabajadores conserveros de frutas y hortalizas y trabajadores de la elaboración de bebidas no alcohólicas' },
  { code: '7706', label: 'Trabajadores de la elaboración de bebidas alcohólicas distintas del vino' },
  { code: '7707', label: 'Trabajadores de la elaboración del vino' },
  { code: '7708', label: 'Preparadores y elaboradores del tabaco y sus productos' },
  { code: '7709', label: 'Catadores y clasificadores de alimentos y bebidas' },
  { code: '7811', label: 'Trabajadores del tratamiento de la madera' },
  { code: '7812', label: 'Ajustadores y operadores de máquinas para trabajar la madera' },
  { code: '7820', label: 'Ebanistas y trabajadores afines' },
  { code: '7831', label: 'Sastres, modistos, peleteros y sombrereros' },
  { code: '7832', label: 'Patronistas para productos en textil y piel' },
  { code: '7833', label: 'Cortadores de tejidos, cuero, piel y otros materiales' },
  { code: '7834', label: 'Costureros a mano, bordadores y afines' },
  { code: '7835', label: 'Tapiceros, colchoneros y afines' },
  { code: '7836', label: 'Curtidores y preparadores de pieles' },
  { code: '7837', label: 'Zapateros y afines' },
  { code: '7891', label: 'Buceadores' },
  { code: '7892', label: 'Pegadores' },
  { code: '7893', label: 'Clasificadores y probadores de productos (excepto alimentos, bebidas y tabaco)' },
  { code: '7894', label: 'Fumigadores y otros controladores de plagas y malas hierbas' },
  { code: '7899', label: 'Oficiales, operarios y artesanos de otros oficios no clasificados bajo otros epígrafes' },
  { code: '8111', label: 'Mineros y otros operadores en instalaciones mineras' },
  { code: '8112', label: 'Operadores en instalaciones para la preparación de minerales y rocas' },
  { code: '8113', label: 'Sondistas y trabajadores afines' },
  { code: '8114', label: 'Operadores de maquinaria para fabricar productos derivados de minerales no metálicos' },
  { code: '8121', label: 'Operadores en instalaciones para la obtención y transformación de metales' },
  { code: '8122', label: 'Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales' },
  { code: '8131', label: 'Operadores en plantas industriales químicas' },
  { code: '8132', label: 'Operadores de máquinas para fabricar productos farmacéuticos, cosméticos y afines' },
  { code: '8133', label: 'Operadores de laboratorios fotográficos y afines' },
  { code: '8141', label: 'Operadores de máquinas para fabricar productos de caucho y derivados de resinas naturales' },
  { code: '8142', label: 'Operadores de máquinas para fabricar productos de material plástico' },
  { code: '8143', label: 'Operadores de máquinas para fabricar productos de papel y cartón' },
  { code: '8144', label: 'Operadores de serrerías, de máquinas de fabricación de tableros y de instalaciones afines para el tratamiento de la madera y el corcho' },
  { code: '8145', label: 'Operadores en instalaciones para la preparación de pasta de papel y fabricación de papel' },
  { code: '8151', label: 'Operadores de máquinas para preparar fibras, hilar y devanar' },
  { code: '8152', label: 'Operadores de telares y otras máquinas tejedoras' },
  { code: '8153', label: 'Operadores de máquinas de coser y bordar' },
  { code: '8154', label: 'Operadores de máquinas de blanquear, teñir, estampar y acabar textiles' },
  { code: '8155', label: 'Operadores de máquinas para tratar pieles y cuero' },
  { code: '8156', label: 'Operadores de máquinas para la fabricación del calzado, marroquinería y guantería de piel' },
  { code: '8159', label: 'Operadores de máquinas para fabricar productos textiles no clasificados bajo otros epígrafes' },
  { code: '8160', label: 'Operadores de máquinas para elaborar productos alimenticios, bebidas y tabaco' },
  { code: '8170', label: 'Operadores de máquinas de lavandería y tintorería' },
  { code: '8191', label: 'Operadores de hornos e instalaciones de vidriería y cerámica' },
  { code: '8192', label: 'Operadores de calderas y máquinas de vapor' },
  { code: '8193', label: 'Operadores de máquinas de embalaje, embotellamiento y etiquetado' },
  { code: '8199', label: 'Operadores de instalaciones y maquinaria fijas no clasificados bajo otros epígrafes' },
  { code: '8201', label: 'Ensambladores de maquinaria mecánica' },
  { code: '8202', label: 'Ensambladores de equipos eléctricos y electrónicos' },
  { code: '8209', label: 'Montadores y ensambladores no clasificados en otros epígrafes' },
  { code: '8311', label: 'Maquinistas de locomotoras' },
  { code: '8312', label: 'Agentes de maniobras ferroviarias' },
  { code: '8321', label: 'Operadores de maquinaria agrícola móvil' },
  { code: '8322', label: 'Operadores de maquinaria forestal móvil' },
  { code: '8331', label: 'Operadores de maquinaria de movimientos de tierras y equipos similares' },
  { code: '8332', label: 'Operadores de grúas, montacargas y de maquinaria similar de movimiento de materiales' },
  { code: '8333', label: 'Operadores de carretillas elevadoras' },
  { code: '8340', label: 'Marineros de puente, marineros de máquinas y afines' },
  { code: '8411', label: 'Conductores propietarios de automóviles, taxis y furgonetas' },
  { code: '8412', label: 'Conductores asalariados de automóviles, taxis y furgonetas' },
  { code: '8420', label: 'Conductores de autobuses y tranvías' },
  { code: '8431', label: 'Conductores propietarios de camiones' },
  { code: '8432', label: 'Conductores asalariados de camiones' },
  { code: '8440', label: 'Conductores de motocicletas y ciclomotores' },
  { code: '9100', label: 'Empleados domésticos' },
  { code: '9210', label: 'Personal de limpieza de oficinas, hoteles y otros establecimientos similares' },
  { code: '9221', label: 'Limpiadores en seco a mano y afines' },
  { code: '9222', label: 'Limpiadores de vehículos' },
  { code: '9223', label: 'Limpiadores de ventanas' },
  { code: '9229', label: 'Otro personal de limpieza' },
  { code: '9310', label: 'Ayudantes de cocina' },
  { code: '9320', label: 'Preparadores de comidas rápidas' },
  { code: '9410', label: 'Vendedores callejeros' },
  { code: '9420', label: 'Repartidores de publicidad, limpiabotas y otros trabajadores de oficios callejeros' },
  { code: '9431', label: 'Ordenanzas' },
  { code: '9432', label: 'Mozos de equipaje y afines' },
  { code: '9433', label: 'Repartidores, recadistas y mensajeros a pie' },
  { code: '9434', label: 'Lectores de contadores y recaudadores de máquinas recreativas y expendedoras' },
  { code: '9441', label: 'Recogedores de residuos' },
  { code: '9442', label: 'Clasificadores de desechos, operarios de punto limpio y recogedores de chatarra' },
  { code: '9443', label: 'Barrenderos y afines' },
  { code: '9490', label: 'Otras ocupaciones elementales' },
  { code: '9511', label: 'Peones agrícolas (excepto en huertas, invernaderos, viveros y jardines)' },
  { code: '9512', label: 'Peones agrícolas en huertas, invernaderos, viveros y jardines' },
  { code: '9520', label: 'Peones ganaderos' },
  { code: '9530', label: 'Peones agropecuarios' },
  { code: '9541', label: 'Peones de la pesca' },
  { code: '9542', label: 'Peones de la acuicultura' },
  { code: '9543', label: 'Peones forestales y de la caza' },
  { code: '9601', label: 'Peones de obras públicas' },
  { code: '9602', label: 'Peones de la construcción de edificios' },
  { code: '9603', label: 'Peones de la minería, canteras y otras industrias extractivas' },
  { code: '9700', label: 'Peones de las industrias manufactureras' },
  { code: '9811', label: 'Peones del transporte de mercancías y descargadores' },
  { code: '9812', label: 'Conductores de vehículos de tracción animal para el transporte de personas y similares' },
  { code: '9820', label: 'Reponedores' },
]

export function sepeOcupacionLabel(code: string): string {
  return SEPE_OCUPACIONES.find((o) => o.code === code)?.label ?? code
}
