export const solicitudes = {
  page: {
    eyebrow: 'Administración',
    title: 'Solicitudes',
    description:
      'Enlaces de acceso al formulario de alta de autónomo para tus contactos.',
  },
  altaAutonomo: {
    newButton: 'Nueva solicitud',
    modalTitle: 'Nueva solicitud de alta de autónomo',
    modalDescription:
      'Elige un contacto de Odoo: generaremos un enlace privado y se lo enviaremos por correo con la fecha de caducidad. Solo aparecen contactos que todavía no son clientes en el portal.',
    clientLabel: 'Contacto',
    clientPlaceholder: 'Selecciona un contacto de Odoo',
    loading: 'Cargando contactos desde Odoo…',
    unavailable: 'Odoo no está configurado. No se pueden crear solicitudes sin conexión a Odoo.',
    error: 'No pudimos cargar los contactos de Odoo. Inténtalo de nuevo.',
    empty:
      'No hay contactos de Odoo disponibles (los que ya son clientes no aparecen aquí).',
    createButton: 'Generar y enviar enlace',
    creating: 'Enviando…',
    generated: 'Enlace generado y enviado al correo del contacto',
    generatedStateTitle: 'Solicitud creada y enviada',
    generatedStateDescription:
      'Hemos enviado el enlace al correo del contacto. También puedes copiarlo aquí si lo necesitas.',
    generateError: 'No se pudo generar o enviar el enlace. Inténtalo de nuevo.',
    copyLink: 'Copiar enlace',
    linkCopied: 'Enlace copiado',
    copyLinkError: 'No se pudo copiar el enlace. Cópialo manualmente.',
  },
  list: {
    filterPending: 'Pendientes',
    filterAll: 'Todas',
    emptyPendingTitle: 'Sin solicitudes pendientes',
    emptyPendingDescription:
      'Cuando generes un enlace activo para un contacto, aparecerá aquí.',
    emptyAllTitle: 'Sin solicitudes',
    emptyAllDescription: 'Aún no se ha generado ningún enlace de alta de autónomo.',
    columns: {
      client: 'Contacto',
      email: 'Email',
      token: 'Código',
      expires: 'Caduca',
      actions: 'Acciones',
    },
    token: {
      show: 'Mostrar código',
      hide: 'Ocultar código',
      copy: 'Copiar código',
      copied: 'Código copiado',
      copyError: 'No se pudo copiar el código. Cópialo manualmente.',
      hiddenHint: 'Código oculto',
    },
    status: {
      active: 'Pendiente',
      used: 'Completada',
      revoked: 'Revocada',
      expired: 'Caducada',
    },
    actions: {
      sendLink: 'Enviar enlace',
      sendingLink: 'Enviando…',
      revoke: 'Revocar',
      delete: 'Eliminar',
      revoking: 'Revocando…',
      deleting: 'Eliminando…',
    },
    revokeSuccess: 'Solicitud revocada',
    revokeError: 'No se pudo revocar la solicitud',
    deleteSuccess: 'Solicitud eliminada',
    deleteError: 'No se pudo eliminar la solicitud',
    deleteConfirm:
      '¿Eliminar esta solicitud? El enlace dejará de existir y no se podrá recuperar.',
    resendSuccess: 'Enlace reenviado',
    resendError: 'No se pudo reenviar el enlace',
    unknownClient: 'Sin nombre',
  },
  detail: {
    back: 'Volver a solicitudes',
    eyebrow: 'Solicitud de Onboarding',
    progressTitle: 'Progreso del envío',
    steps: {
      sent: 'Enviado',
      delivered: 'Entregado',
      opened: 'Abierto',
      clicked: 'Clicado',
    },
    openedBanner: {
      title: 'Correo abierto',
      note: 'El estado "Abierto" puede no ser exacto: algunos gestores de correo precargan imágenes automáticamente.',
    },
    failure: {
      bounced: {
        title: 'Correo rebotado',
        note: 'El correo no llegó al destinatario. Comprueba que la dirección sea correcta.',
      },
      complained: {
        title: 'Marcado como spam',
        note: 'El destinatario ha marcado este correo como spam.',
      },
    },
    notSentYet: 'Aún no se ha enviado ningún correo para esta solicitud.',
    nav: {
      previous: 'Anterior',
      next: 'Siguiente',
      previousHint: 'Solicitud anterior',
      nextHint: 'Solicitud siguiente',
      buttonHintIdle: '{action}. Mantén {modifier} para ver atajos.',
      buttonHintActive: '{action} ({shortcut})',
    },
    infoTitle: 'Datos de la solicitud',
    fields: {
      client: 'Contacto',
      email: 'Email',
      code: 'Código',
      status: 'Estado',
      created: 'Creada',
      expires: 'Caduca',
    },
  },
} as const
