/** Thumbnail/preview PNG (gradient placeholder, ~200 bytes). */
export const MOCK_IMAGE_JPEG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA' +
  'B3RJTUUH6QcIDBQaLN3PngAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVAA' +
  'f+NNAAAADElEQVR42u3BAQEAAACCIP+vbkhAAQAAwJ8GAAE0BjrxAAAAAElFTkSuQmCC'

/** Minimal valid PDF with "Documento demo" text. */
export const MOCK_PDF_BASE64 =
  'JVBERi0xLjQKJeLjz9MKMyAwIG9iago8PC9UeXBlIC9QYWdlCi9QYXJlbnQgMSAwIFIKL01lZGlh' +
  'Qm94IFswIDAgNjEyIDc5Ml0KL1Jlc291cmNlcyAyIDAgUgovQ29udGVudHMgNCAwIFI+PgplbmRv' +
  'YmoKNCAwIG9iago8PC9MZW5ndGggNDQ+PnN0cmVhbQpCVApxIDEwMCB3IDUwMCBoIDc1MCBUZAov' +
  'RjEgMTIgVGYKKERvY3VtZW50byBkZW1vKSBUagpFVCBlbmRzdHJlYW0KZW5kb2JqCjIgMCBvYmoK' +
  'PDwvRm9udCA8PC9GMSA1IDAgUj4+Pj4KZW5kb2JqCjUgMCBvYmoKPDwvVHlwZSAvRm9udAovU3Vi' +
  'dHlwZSAvVHlwZTEKL0Jhc2VGb250IC9IZWx2ZXRpY2E+PgplbmRvYmoKMSAwIG9iago8PC9UeXBl' +
  'IC9QYWdlcwovS2lkcyBbMyAwIFJdCj4+CmVuZG9iago2IDAgb2JqCjw8L1R5cGUgL0NhdGFsb2cvUGFn' +
  'ZXMgMSAwIFI+PgplbmRvYmoKMiAwIG9iago8PC9DcmVhdG9yIChTeW50aWEgZGVtbyk+PgplbmRvYmoK' +
  'eHJlZgowIDcKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwNDE0IDAwMDAwIG4gCjAwMDAwMDAzNjYg' +
  'MDAwMDAgbiAKMDAwMDAwMDAxNSAwMDAwMDAgbiAKMDAwMDAwMDExMCAwMDAwMDAgbiAKMDAwMDAwMDIw' +
  'MyAwMDAwMDAgbiAKMDAwMDAwMDQ2MyAwMDAwMDAgbiAKdHJhaWxlcgo8PC9TaXplIDcKL1Jvb3QgNiAw' +
  'IFIKPj4Kc3RhcnR4cmVmCjU0NwolJUVPRg=='

export function mockImageDataUrl(): string {
  return `data:image/png;base64,${MOCK_IMAGE_JPEG_BASE64}`
}
